// <auto-generated />
using BusManagementApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ParkingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241128001056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusManagementApp.Bus", b =>
                {
                    b.Property<long>("IdBus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdBus"));

                    b.Property<string>("BusMark")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.Property<string>("NumberSign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TheDriver")
                        .HasColumnType("bigint");

                    b.HasKey("IdBus");

                    b.HasIndex("NumberSign")
                        .IsUnique();

                    b.HasIndex("TheDriver");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("BusManagementApp.Driver", b =>
                {
                    b.Property<long>("IdDriver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdDriver"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryDriverLicence")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdDriver");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("BusManagementApp.Bus", b =>
                {
                    b.HasOne("BusManagementApp.Driver", "Driver")
                        .WithMany("Buses")
                        .HasForeignKey("TheDriver")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BusManagementApp.Driver", b =>
                {
                    b.Navigation("Buses");
                });
#pragma warning restore 612, 618
        }
    }
}
